// Dev helper: UNIQLO items from the wardrobe, size / colour switch, tuck in and out, in 3D and 寫真.
import { chromium } from "playwright";
const browser = await chromium.launch({ args: ["--use-angle=swiftshader", "--enable-unsafe-swiftshader"] });
const page = await browser.newPage({ viewport: { width: 1280, height: 860 } });
const errs = [];
page.on("pageerror", (e) => errs.push(e.message));
page.on("console", (m) => { if (m.type() === "error" && !/^INFO:/.test(m.text())) errs.push(m.text()); });
const idle = () => page.waitForFunction(() => document.querySelector("#busy").hidden, null, { timeout: 120000 });
await page.goto("http://localhost:5391/");
await page.waitForFunction(() => window.__ready === true, null, { timeout: 120000 });
await page.uncheck("#quality");
await page.click('#tabs button[data-tab="wear"]');
await page.waitForFunction(() => document.querySelectorAll("#wardrobe-list li").length >= 17, null, { timeout: 60000 });
console.log("wardrobe:", (await page.$$eval("#wardrobe-list li span", (xs) => xs.map((x) => x.textContent))).join(" / "));
const wearItem = async (name) => { await page.click(`#wardrobe-list li:has-text('${name}') button:has-text('穿上')`); await page.waitForTimeout(300); await idle(); };
await wearItem("UNIQLO 圓領 T 恤");
await wearItem("直筒牛仔褲");
const info = () => page.evaluate(() => window.__closet.worn.map((w) => `${w.spec.type}:${w.spec.size ?? "-"}${w.spec.tucked ? ":tucked" : ""}`).join(" "));
console.log("worn:", await info(), "| label:", await page.textContent("#worn-list li:first-child span"));
await page.waitForTimeout(800);
await page.screenshot({ path: "_artifacts/tuck-out-3d.png" });
await page.click("#worn-list button.tuck");
await page.waitForTimeout(300); await idle(); await page.waitForTimeout(800);
console.log("after tuck:", await info());
await page.screenshot({ path: "_artifacts/tuck-in-3d.png" });
await page.selectOption("#look-style", "photo");
await page.waitForTimeout(300); await idle(); await page.waitForTimeout(500);
await page.screenshot({ path: "_artifacts/tuck-in-photo.png" });
await page.click("#worn-list button.tuck");
await page.waitForTimeout(300); await idle(); await page.waitForTimeout(500);
await page.screenshot({ path: "_artifacts/tuck-out-photo.png" });
// colour + size switch on the UNIQLO tee
await page.selectOption("#worn-list select.uq-color", "3");
await page.waitForTimeout(300); await idle();
const sizes = await page.$$eval("#worn-list select.uq-size option", (os) => os.map((o) => o.textContent));
console.log("sizes:", sizes.join(" "));
await page.selectOption("#worn-list select.uq-size", "XL");
await page.waitForTimeout(300); await idle(); await page.waitForTimeout(500);
console.log("after XL:", await info(), "| label:", await page.textContent("#worn-list li:has(select.uq-size) span"));
await page.screenshot({ path: "_artifacts/uq-xl-photo.png" });
await page.selectOption("#look-style", "3d");
console.log(errs.join("\n") || "no errors");
await browser.close();
