// Dev helper: a skirt in 3D with feet apart / together and sitting -> _artifacts/s3d-*.png
import { chromium } from "playwright";
const [item = "雪紡長裙"] = process.argv.slice(2);
const browser = await chromium.launch({ args: ["--use-angle=swiftshader", "--enable-unsafe-swiftshader"] });
const page = await browser.newPage({ viewport: { width: 1180, height: 860 } });
const errs = [];
page.on("pageerror", (e) => errs.push(e.message));
const idle = () => page.waitForFunction(() => document.querySelector("#busy").hidden && window.__closet.poseSettled, null, { timeout: 120000 });
const clip = { x: 180, y: 70, width: 520, height: 790 };
await page.goto("http://localhost:5391/");
await page.waitForFunction(() => window.__ready === true, null, { timeout: 120000 });
await page.uncheck("#quality");
if (process.env.NODRAPE) await page.evaluate(() => { globalThis.__noDrape = true; });
await page.selectOption("#look-style", "3d");
await page.click('#tabs button[data-tab="wear"]');
await page.waitForFunction(() => document.querySelectorAll("#wardrobe-list li").length >= 20, null, { timeout: 60000 });
const setStance = async (v) => { await page.$eval("#stance", (el, v) => { el.value = String(v); el.dispatchEvent(new Event("input")); }, v); await page.waitForTimeout(400); await idle(); await page.waitForTimeout(900); };
await setStance(1);
await page.click(`#wardrobe-list li:has-text("${item}") button:has-text('穿上')`);
await page.waitForTimeout(300); await idle(); await page.waitForTimeout(900);
await page.screenshot({ path: "_artifacts/s3d-0.png", clip });
await setStance(0);
await page.screenshot({ path: "_artifacts/s3d-1.png", clip });
await page.click("#pose-sit");
await page.waitForTimeout(400); await idle(); await page.waitForTimeout(1500);
await page.screenshot({ path: "_artifacts/s3d-2.png", clip });
await page.evaluate(() => { window.__closet.avatar.group.rotation.y = 1.1; });
await page.waitForTimeout(700);
await page.screenshot({ path: "_artifacts/s3d-3.png", clip });
await page.evaluate(() => { window.__closet.avatar.group.rotation.y = 0; });
await page.click("#pose-stand");
await setStance(1);
console.log(errs.join("\n") || "no errors");
await browser.close();
